
CREATE TABLE ANSWERS
(
  ANSWER_ID VARCHAR(50) NOT NULL COMMENT '유니크ID',
  ANSWER    VARCHAR(50) NOT NULL COMMENT '답항',
  PRIMARY KEY (ANSWER_ID)
) COMMENT '답항';

CREATE TABLE QUESTIONS
(
  QUESTION_ID VARCHAR(50)  NOT NULL COMMENT '유니크ID',
  QUESTION    VARCHAR(500) NOT NULL COMMENT '문항',
  PRIMARY KEY (QUESTION_ID)
) COMMENT '문항';

CREATE TABLE Statistics
(
  STATISTICS_ID VARCHAR(50) NOT NULL COMMENT '유니크ID',
  USER_ID       VARCHAR(50) NOT NULL COMMENT '유니크ID',
  QUESTION_ID   VARCHAR(50) NOT NULL COMMENT '유니크ID',
  ANSWER_ID     VARCHAR(50) NOT NULL COMMENT '유니크ID',
  PRIMARY KEY (STATISTICS_ID)
) COMMENT '통계';

CREATE TABLE USERS
(
  USER_ID VARCHAR(50) NOT NULL COMMENT '유니크ID',
  USER    VARCHAR(50) NOT NULL COMMENT '이름',
  GENDER  VARCHAR(50) NOT NULL COMMENT '성별',
  AGE     INTEGER     NOT NULL COMMENT '나이',
  PRIMARY KEY (USER_ID)
) COMMENT '설문자';

ALTER TABLE Statistics
  ADD CONSTRAINT FK_USERS_TO_Statistics
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID);

ALTER TABLE Statistics
  ADD CONSTRAINT FK_QUESTIONS_TO_Statistics
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTIONS (QUESTION_ID);

ALTER TABLE Statistics
  ADD CONSTRAINT FK_ANSWERS_TO_Statistics
    FOREIGN KEY (ANSWER_ID)
    REFERENCES ANSWERS (ANSWER_ID);
